spring.application.name=HelloSpringMVCAndData

# Setting up Spring Boot Actuator to see different metrics and health stats in our app
# Actuator works by exposing endpoints we can request to in order to get information
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

#DB Setup properties--------------

#Points to our Database
spring.datasource.url=jdbc:sqlite:TacoAndUser.db?foreign_keys=on

#Using the sqlite Driver (need a dependency for sqlite)
spring.datasource.driver-class-name=org.sqlite.JDBC

#Shows any SQL running in your console - great for debugs
spring.jpa.show-sql=true

#Telling Spring Data we want to use SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

#The DDL config for what happens when we run our app
#update == any changes to the DB entities change in the Database
#create == the entire DB gets wiped and recreated
spring.jpa.hibernate.ddl-auto=update

#Trying to get startup to go faster
spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.maximumPoolSize=2
spring.datasource.hikari.connectionTimeout=10000
spring.datasource.hikari.initializationFailTimeout=0